[package]
name = "rpg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13.1"
bevy-scene-hook = "10.0.0"
lazy_static = "1.4.0"
rand = "0.8.5"
