use crate::world::map::{Map, Tile, TileType, WallType};

pub fn generate_map() -> Map {
    Map { tiles: vec![
        vec![
            Tile::new(
                TileType::Dirt,
                WallType::Regular,
                WallType::None,
                WallType::None,
                WallType::Regular
            ),
            Tile::new(
                TileType::Dirt,
                WallType::None,
                WallType::None,
                WallType::None,
                WallType::Regular
            ),
            Tile::new(
                TileType::Dirt,
                WallType::None,
                WallType::None,
                WallType::None,
                WallType::Regular
            ),
            Tile::new(
                TileType::Dirt,
                WallType::None,
                WallType::None,
                WallType::None,
                WallType::Regular
            ),
            Tile::new(
                TileType::Dirt,
                WallType::None,
                WallType::None,
                WallType::Regular,
                WallType::Regular
            )
        ],
        vec![
            Tile::new(
                TileType::Wood,
                WallType::Regular,
                WallType::None,
                WallType::None,
                WallType::None
            ),
            Tile::new(
                TileType::Wood,
                WallType::None,
                WallType::None,
                WallType::None,
                WallType::None
            ),
            Tile::new(
                TileType::Wood,
                WallType::None,
                WallType::None,
                WallType::None,
                WallType::None
            ),
            Tile::new(
                TileType::Wood,
                WallType::None,
                WallType::None,
                WallType::None,
                WallType::None
            ),
            Tile::new(
                TileType::Wood,
                WallType::None,
                WallType::None,
                WallType::Regular,
                WallType::None
            ),
        ],
        vec![
            Tile::new(
                TileType::Tiled,
                WallType::Regular,
                WallType::Regular,
                WallType::None,
                WallType::None
            ),
            Tile::new(
                TileType::Tiled,
                WallType::None,
                WallType::Regular,
                WallType::None,
                WallType::None
            ),
            Tile::new(
                TileType::None,
                WallType::None,
                WallType::Regular,
                WallType::None,
                WallType::None
            ),
            Tile::new(
                TileType::Tiled,
                WallType::None,
                WallType::Regular,
                WallType::None,
                WallType::None
            ),
            Tile::new(
                TileType::Tiled,
                WallType::None,
                WallType::Regular,
                WallType::Regular,
                WallType::None
            )
        ]
    ] }
}